#!/usr/bin/env bash
# Usage: script/run <ARGV>
# Run the application using specified arguments, or none.

set -e

script/bootstrap

echo "Starting application..."

bin/spoon $1 $2 $3 $4 $5 $6 $7 $8 $9
